# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: skesiraju
google_analytics: UA-71590040-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Code

description: Blog
author:
  name: Santosh
  email: kcraj2@gmail.com 
  github: skesiraju
  twitter: skesiraju
  linkedin: santoshkesiraju
  bio: Researcher
  email_md5: 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
